# stat_config.py — Python mirror of static/js/stat_config.js
# Used by Flask routes for server-side percentile direction checks.
# Keys match the stat_key values used in percentile_rankings table.

STAT_CONFIG = {
    # Standard batting — higher = better
    'games':    {'label': 'G',     'higher_is_better': True,  'format': 'int',  'group': 'standard_batting'},
    'pa':       {'label': 'PA',    'higher_is_better': True,  'format': 'int',  'group': 'standard_batting'},
    'ab':       {'label': 'AB',    'higher_is_better': True,  'format': 'int',  'group': 'standard_batting'},
    'r':        {'label': 'R',     'higher_is_better': True,  'format': 'int',  'group': 'standard_batting'},
    'h':        {'label': 'H',     'higher_is_better': True,  'format': 'int',  'group': 'standard_batting'},
    'doubles':  {'label': '2B',    'higher_is_better': True,  'format': 'int',  'group': 'standard_batting'},
    'triples':  {'label': '3B',    'higher_is_better': True,  'format': 'int',  'group': 'standard_batting'},
    'hr':       {'label': 'HR',    'higher_is_better': True,  'format': 'int',  'group': 'standard_batting'},
    'rbi':      {'label': 'RBI',   'higher_is_better': True,  'format': 'int',  'group': 'standard_batting'},
    'bb':       {'label': 'BB',    'higher_is_better': True,  'format': 'int',  'group': 'standard_batting'},
    'avg':      {'label': 'AVG',   'higher_is_better': True,  'format': 'avg',  'group': 'standard_batting'},
    'obp':      {'label': 'OBP',   'higher_is_better': True,  'format': 'avg',  'group': 'standard_batting'},
    'slg':      {'label': 'SLG',   'higher_is_better': True,  'format': 'avg',  'group': 'standard_batting'},
    'ops':      {'label': 'OPS',   'higher_is_better': True,  'format': 'ops',  'group': 'standard_batting'},
    'so':       {'label': 'SO',    'higher_is_better': False, 'format': 'int',  'group': 'standard_batting'},
    # Advanced batting — higher = better
    'ops_plus': {'label': 'OPS+',  'higher_is_better': True,  'format': 'int',  'group': 'advanced_batting'},
    'iso':      {'label': 'ISO',   'higher_is_better': True,  'format': 'avg',  'group': 'advanced_batting'},
    'babip':    {'label': 'BABIP', 'higher_is_better': True,  'format': 'avg',  'group': 'advanced_batting'},
    'bb_pct':   {'label': 'BB%',   'higher_is_better': True,  'format': 'pct',  'group': 'advanced_batting'},
    'bb_per_k': {'label': 'BB/K',  'higher_is_better': True,  'format': 'dec2', 'group': 'advanced_batting'},
    'rc':       {'label': 'RC',    'higher_is_better': True,  'format': 'dec1', 'group': 'advanced_batting'},
    'k_pct':    {'label': 'K%',    'higher_is_better': False, 'format': 'pct',  'group': 'advanced_batting'},
    'ab_per_hr':{'label': 'AB/HR', 'higher_is_better': False, 'format': 'dec1', 'group': 'advanced_batting'},
    # Standard pitching — higher = better
    'g_p':      {'label': 'G',     'higher_is_better': True,  'format': 'int',  'group': 'standard_pitching'},
    'gs':       {'label': 'GS',    'higher_is_better': True,  'format': 'int',  'group': 'standard_pitching'},
    'w':        {'label': 'W',     'higher_is_better': True,  'format': 'int',  'group': 'standard_pitching'},
    'sv':       {'label': 'SV',    'higher_is_better': True,  'format': 'int',  'group': 'standard_pitching'},
    'ip':       {'label': 'IP',    'higher_is_better': True,  'format': 'dec1', 'group': 'standard_pitching'},
    'k_p':      {'label': 'K',     'higher_is_better': True,  'format': 'int',  'group': 'standard_pitching'},
    'l':        {'label': 'L',     'higher_is_better': False, 'format': 'int',  'group': 'standard_pitching'},
    'era':      {'label': 'ERA',   'higher_is_better': False, 'format': 'era',  'group': 'standard_pitching'},
    'whip':     {'label': 'WHIP',  'higher_is_better': False, 'format': 'era',  'group': 'standard_pitching'},
    'bb_p':     {'label': 'BB',    'higher_is_better': False, 'format': 'int',  'group': 'standard_pitching'},
    'h_p':      {'label': 'H',     'higher_is_better': False, 'format': 'int',  'group': 'standard_pitching'},
    'hr_p':     {'label': 'HR',    'higher_is_better': False, 'format': 'int',  'group': 'standard_pitching'},
    'baa':      {'label': 'BAA',   'higher_is_better': False, 'format': 'avg',  'group': 'standard_pitching'},
    # Advanced pitching — higher = better
    'era_plus': {'label': 'ERA+',  'higher_is_better': True,  'format': 'int',  'group': 'advanced_pitching'},
    'k_per_6':  {'label': 'K/6',   'higher_is_better': True,  'format': 'dec2', 'group': 'advanced_pitching'},
    'k_pct_p':  {'label': 'K%',    'higher_is_better': True,  'format': 'pct',  'group': 'advanced_pitching'},
    'lob_pct':  {'label': 'LOB%',  'higher_is_better': True,  'format': 'pct',  'group': 'advanced_pitching'},
    'bb_per_6': {'label': 'BB/6',  'higher_is_better': False, 'format': 'dec2', 'group': 'advanced_pitching'},
    'hr_per_6': {'label': 'HR/6',  'higher_is_better': False, 'format': 'dec2', 'group': 'advanced_pitching'},
    'bb_pct_p': {'label': 'BB%',   'higher_is_better': False, 'format': 'pct',  'group': 'advanced_pitching'},
    'babip_p':  {'label': 'BABIP', 'higher_is_better': False, 'format': 'avg',  'group': 'advanced_pitching'},
    # HQ batting
    'pa_hq':      {'label': 'PA',    'higher_is_better': True,  'format': 'int',  'group': 'hq_batting'},
    'avg_hq':     {'label': 'AVG',   'higher_is_better': True,  'format': 'avg',  'group': 'hq_batting'},
    'obp_hq':     {'label': 'OBP',   'higher_is_better': True,  'format': 'avg',  'group': 'hq_batting'},
    'slg_hq':     {'label': 'SLG',   'higher_is_better': True,  'format': 'avg',  'group': 'hq_batting'},
    'ops_hq':     {'label': 'OPS',   'higher_is_better': True,  'format': 'ops',  'group': 'hq_batting'},
    'hr_hq':      {'label': 'HR',    'higher_is_better': True,  'format': 'int',  'group': 'hq_batting'},
    'bb_pct_hq':  {'label': 'BB%',   'higher_is_better': True,  'format': 'pct',  'group': 'hq_batting'},
    'iso_hq':     {'label': 'ISO',   'higher_is_better': True,  'format': 'avg',  'group': 'hq_batting'},
    'babip_hq':   {'label': 'BABIP', 'higher_is_better': True,  'format': 'avg',  'group': 'hq_batting'},
    'k_pct_hq':   {'label': 'K%',    'higher_is_better': False, 'format': 'pct',  'group': 'hq_batting'},
    # HQ pitching
    'bf_hq':       {'label': 'BF',    'higher_is_better': True,  'format': 'int',  'group': 'hq_pitching'},
    'era_hq':      {'label': 'ERA',   'higher_is_better': False, 'format': 'era',  'group': 'hq_pitching'},
    'obp_hq_p':    {'label': 'OBP',   'higher_is_better': False, 'format': 'avg',  'group': 'hq_pitching'},
    'baa_hq':      {'label': 'BAA',   'higher_is_better': False, 'format': 'avg',  'group': 'hq_pitching'},
    'k_pct_hq_p':  {'label': 'K%',    'higher_is_better': True,  'format': 'pct',  'group': 'hq_pitching'},
    'bb_pct_hq_p': {'label': 'BB%',   'higher_is_better': False, 'format': 'pct',  'group': 'hq_pitching'},
    'k_per_6_hq':  {'label': 'K/6',   'higher_is_better': True,  'format': 'dec2', 'group': 'hq_pitching'},
    'bb_per_6_hq': {'label': 'BB/6',  'higher_is_better': False, 'format': 'dec2', 'group': 'hq_pitching'},
    'hr_per_6_hq': {'label': 'HR/6',  'higher_is_better': False, 'format': 'dec2', 'group': 'hq_pitching'},
}
